### ISSUE TITLE
Resource links from HEAR index page

### ISSUE THREAD

**Issue by asimong** [Cetis/xcri#12]
On the HEAR index page, there are several dead links to documents on alanpaull.co.uk. We have the original materials for several of these: need to host them on our servers somewhere and link to these versions when available.

For all linked resources, where no version is able to be found, or there is no version we are permitted to host and make public, delete the link.

**Comment by ds10** [comment]
moved to HEAR repo: https://github.com/Cetis/hear/issues/6
